(define (even n)
  (= (remainder n 2) 0)
)

(define (fast_expt_iter b n a)
  (cond ((= n 0) a)
        ((even n)
         (fast_expt_iter (square b) (/ n 2) a))
        (else (fast_expt_iter b (- n 1) (* b a)))
  )
)

(define (fast_expt b n)
  (fast_expt_iter b n 1)
)
