(load "../Chapter_1/1.2/Example_4/fib_by_iteration.scm")
(define (even-fibs-list n)
  (define (next k)
    (if (> k n) '()
        (let ((f (fib k)))
          (if (even? f)
              (cons f (next (+ k 1)))
              (next (+ k 1))))))
  (next 0)
